require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocommands"

spec "user.colorscheme"
spec "user.miniicons"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.metals"
spec "user.lsp-saga"
spec "user.lsp-signature"
-- spec "user.navic"
spec "user.fzf-lua"
spec "user.none-ls"
spec "user.illuminate"
spec "user.neotree"
spec "user.lualine"
spec "user.whichkey"
-- spec "user.dap"
spec "user.cmp"
-- spec "user.autopairs"
spec "user.comment"
spec "user.gitsigns"
spec "user.neogit"
spec "user.indentline"
spec "user.alpha"
spec "user.project"
spec "user.toggleterm"
spec "user.bufdelete"
spec "user.bufjump"

-- Extras
spec "user.extras.notify"
spec "user.extras.colorizer"
-- spec "user.extras.neoscroll"
-- spec "user.extras.copilot"
spec "user.extras.modicator"
spec "user.extras.bqf"
spec "user.extras.ufo"
spec "user.extras.nui"
spec "user.extras.dressing"
-- spec "user.extras.surround"
spec "user.extras.eyeliner"
spec "user.extras.numb"
spec "user.extras.fidget"
spec "user.extras.neotab"
-- spec "user.extras.neotest"
spec "user.extras.tabby"
-- -- spec "user.extras.test"
spec "user.extras.gitlinker"
spec "user.extras.harpoon"
spec "user.extras.trouble"
spec "user.extras.todo-comments"
-- spec "user.extras.persistence"
spec "user.extras.persisted"
spec "user.extras.rustacean"
spec "user.extras.crates"
spec "user.extras.endwise"
spec "user.extras.markdown"

require "user.lazy"
