- hosts: localhost
  gather_facts: true
  tasks:
    - name: ensure fonts directory
      file:
        path: "{{ lookup('env', 'HOME') }}/.fonts"
        state: directory

    - name: CascadiaCode exists
      shell: "ls {{ lookup('env', 'HOME') }}/.fonts/CascadiaCode*Nerd*Font*Complete*"
      register: hack_exists
      ignore_errors: yes

    - name: Download CascadiaCode
      when: hack_exists is failed
      ansible.builtin.unarchive:
        src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/CascadiaCode.zip
        dest: "{{ lookup('env', 'HOME') }}/.fonts/"
        remote_src: yes

