- name: Install Nerd Font
  hosts: localhost
  gather_facts: true
  vars:
    nerd_font_name: "CascadiaCode"  # Change this to any Nerd Font name, e.g., FiraCode, Hack, etc.
    nerd_font_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/{{ nerd_font_name }}.zip"
    default_fonts_dir: "{{ lookup('env', 'HOME') }}/.fonts"
    macos_fonts_dir: "{{ lookup('env', 'HOME') }}/Library/Fonts"

  pre_tasks:
    - name: Set fonts_dir based on OS
      set_fact:
        fonts_dir: "{{ macos_fonts_dir if ansible_system == 'Darwin' else default_fonts_dir }}"

  tasks:
    - name: Ensure fonts directory exists
      ansible.builtin.file:
        path: "{{ fonts_dir }}"
        state: directory
        mode: '0755'

    - name: Check if {{ nerd_font_name }} Nerd Font is already installed
      ansible.builtin.shell: |
        ls "{{ fonts_dir }}/{{ nerd_font_name }}*Nerd*Font*Complete*" 2>/dev/null
      register: font_check
      changed_when: false
      failed_when: false

    - name: Download and extract {{ nerd_font_name }} Nerd Font
      when: font_check.stdout == ""
      ansible.builtin.unarchive:
        src: "{{ nerd_font_url }}"
        dest: "{{ fonts_dir }}/"
        remote_src: yes
        mode: '0644'

    - name: Update font cache (Linux only)
      when: ansible_system != 'Darwin'
      ansible.builtin.command: fc-cache -fv
      changed_when: true

