theme = "kanagawa"

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
g = { a = "code_action" } # Maps `ga` to show possible code actions

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
